
local envvar_ver = os.getenv("envvar_ver")
local PrgEnv_intel_ver = os.getenv("PrgEnv_intel_ver")
local craype_ver = os.getenv("craype_ver")
local intel_ver = os.getenv("intel_ver")
local cray_mpich_ver = os.getenv("cray_mpich_ver")
local cray_pals_ver = os.getenv("cray_pals_ver")
local cfp_ver = os.getenv("cfp_ver")
local prod_envir_ver = os.getenv("prod_envir_ver")
local prod_util_ver = os.getenv("prod_util_ver")
local libjpeg_ver = os.getenv("libjpeg_ver")
local grib_util_ver = os.getenv("grib_util_ver")
local wgrib2_ver = os.getenv("wgrib2_ver")
local g2tmpl_ver = os.getenv("g2tmpl_ver")
local crtm_ver = os.getenv("crtm_ver")
local esmf_ver = os.getenv("esmf_ver")
local netcdf_ver = os.getenv("netcdf_ver")
local udunits_ver = os.getenv("udunits_ver")
local gsl_ver = os.getenv("gsl_ver")
local nco_ver = os.getenv("nco_ver")
local iobuf_ver = os.getenv("iobuf_ver")
local w3emc_ver = os.getenv("w3emc_ver")
local w3nco_ver = os.getenv("w3nco_ver")
local bacio_ver = os.getenv("bacio_ver")
local sp_ver = os.getenv("sp_ver")
local g2_ver = os.getenv("g2_ver")
local jasper_ver = os.getenv("jasper_ver")
local libpng_ver = os.getenv("libpng_ver")
local zlib_ver = os.getenv("zlib_ver")

load("envvar/"..envvar_ver)
load("PrgEnv-intel/"..PrgEnv_intel_ver)
load("craype/"..craype_ver)
load("intel/"..intel_ver)
load("cray_mpich/"..cray_mpich_ver)
load("cray_pals/"..cray_pals_ver)
load("cfp/"..cfp_ver)
load("prod_envir/"..prod_envir_ver)
load("prod_util/"..prod_util_ver)
load("libjpeg/"..libjpeg_ver)
load("grib_util/"..grib_util_ver)
load("wgrib2/"..wgrib2_ver)
load("g2tmpl/"..g2tmpl_ver)
load("crtm/"..crtm_ver)
load("esmf/"..esmf_ver)
load("netcdf/"..netcdf_ver)
load("udunits/"..udunits_ver)
load("gsl/"..gsl_ver)
load("nco/"..nco_ver)
load("iobuf/"..iobuf_ver)
load("w3emc/"..w3emc_ver)
load("w3nco/"..w3nco_ver)
load("bacio/"..bacio_ver)
load("sp/"..sp_ver)
load("g2/"..g2_ver)
load("jasper/"..jasper_ver)
load("libpng/"..libpng_ver)
load("zlib/"..zlib_ver)
