#!/bin/ksh

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='${PMI_FORK_RANK}: $SECONDS + ' 
date
# 
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA=${DATA:-$DATAROOT/${job}.${pid}}
mkdir $DATA
cd $DATA 

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}

####################################
# SENDECF  - Flag Events on ECF
# SENDDBN  - Issue DBNet Client Calls
# SENDCOM  - Copy files to /com directory
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

#
# Set up model and cycle specific variables
#
export NET=naefs
export RUN=gefs
export fend=384
export finc=3
export fstart=00
export model=ensemble
export GRIB=
export EXT=""
export DBN_ALERT_TYPE=NAEFS_GEFS_GEMPAK

#
# Now set up GEMPAK/NTRANS environment
#
#. /nwprod/gempak/.gempak


#########################
# Specify Execution Areas
#########################

export HOMEnaefs=${HOMEnaefs:-$PACKAGEROOT/naefs.${naefs_ver}}
export EXECnaefs=${EXECnaefs:-$HOMEnaefs/exec}
export FIXnaefs=${FIXnaefs:-$HOMEnaefs/fix}
export USHnaefs=${USHnaefs:-$HOMEnaefs/ush}

setpdy.sh
. ./PDY

export COMIN_ME=${COMIN_ME:-$(compath.py $envir/$NET/${naefs_ver})/${RUN}.${PDY}/${cyc}/pgrb2ap5}
export COMIN_ANL=${COMIN_ANL:-$(compath.py $envir/$NET/${naefs_ver})/${RUN}.${PDYm2}/${cyc}/pgrb2ap5}
export COMOUT=${COMOUT:-$(compath.py -o $NET/${naefs_ver})/${RUN}.${PDY}/gempak}
export COMOUTm2=${COMOUTm2:-$(compath.py -o $NET/${naefs_ver})/${RUN}.${PDYm2}/gempak}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi

if [ ! -f $COMOUTm2 ] ; then
  mkdir -p -m 775 $COMOUTm2
fi
 
env

########################################################
# Execute the script.
mkdir -p $DATA/avg_me $DATA/gfs_me $DATA/gefs_anl
mkdir -p $DATA/avg_me_01 $DATA/avg_mecom $DATA/avg_mecom_01

echo "${HOMEnaefs}/scripts/exnawips_naefs.sh $DATA/avg_me 03 180 ${COMIN_ME} $COMOUT geavg me NAEFS_GEFS_GEMPAK &> $DATA/avg_me/output" >> $DATA/poescript
echo "${HOMEnaefs}/scripts/exnawips_naefs.sh $DATA/avg_me_01 183 384 ${COMIN_ME} $COMOUT geavg me NAEFS_GEFS_GEMPAK &> $DATA/avg_me/output" >> $DATA/poescript
echo "${HOMEnaefs}/scripts/exnawips_naefs.sh $DATA/gfs_me 03 180 ${COMIN_ME} $COMOUT gegfs me NAEFS_GEFS_GEMPAK &> $DATA/gfs_me/output" >> $DATA/poescript
echo "${HOMEnaefs}/scripts/exnawips_naefs.sh $DATA/gefs_anl 00 00 ${COMIN_ANL} $COMOUTm2 gefs glbanl NAEFS_GEFS_GEMPAK &> $DATA/gefs_anl/output" >> $DATA/poescript
echo "${HOMEnaefs}/scripts/exnawips_naefs.sh $DATA/avg_mecom 03 180 ${COMIN_ME} $COMOUT geavg mecom NAEFS_GEFS_GEMPAK &> $DATA/avg_me/output" >> $DATA/poescript
echo "${HOMEnaefs}/scripts/exnawips_naefs.sh $DATA/avg_mecom_01 183 384 ${COMIN_ME} $COMOUT geavg mecom NAEFS_GEFS_GEMPAK &> $DATA/avg_me/output" >> $DATA/poescript
chmod 775 $DATA/poescript

# Execute the script.
$APRUN $DATA/poescript
export err=$?; err_chk

########################################################

cd $DATAROOT

if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
