#!/bin/ksh 
# #######################################################
# Bias Correct FNMOC Global Ensemble Forecast              
# #######################################################

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the sms script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}

set -xa

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-naefs}
export RUN=${RUN:-fens}

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATAROOT: Location of working directory, default to /gpfs/hps2/nco/ops/tmpnwprd
# SENDECF: If the job is to be running using SMS, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to ${COMROOT}/$NET/${envir}
# COM_OUT: Directory for output file, default to ${COMROOT}/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
#####################################################################################

if [ "$RUN_ENVIR" = dev ]      ### For Developers
then
   PARA_CONFIG=${PARA_CONFIG:-${NWROOT}/${direxp}/parm/fnmoc_debias_config}
   . $PARA_CONFIG
fi

export PS4='${PMI_FORK_RANK}: $SECONDS + '
# JY export PS4='${PMI_FORK_RANK}: $SECONDS `basename $0` + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATAROOT=${DATAROOT:-/gpfs/hps2/nco/ops/tmpnwprd}
export DATA=$DATAROOT/${job}.${pid}

mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

export cycle=t${cyc}z

####################################
# File To Log Msgs
####################################

export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

################################################################
# SENDCOM=YES--Copy output file to ${COMROOT}
# SENDECF=YES--Allow to talk back to SMS
# SENDDBN=YES--Alert output file to TOC, set to NO for testing
################################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}          # need to set to NO for testing
export SENDECF=${SENDECF:-YES}

####################################
# Specify Execution Areas
####################################
 
export HOMEfnmoc=${HOMEfnmoc:-${NWROOT}/naefs.${naefs_ver}}
export EXECfnmoc=${EXECfnmoc:-$HOMEfnmoc/exec}
export FIXfnmoc=${FIXfnmoc:-$HOMEfnmoc/fix}
export USHfnmoc=${USHfnmoc:-$HOMEfnmoc/ush}

export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg
export REDOUT='1>>'
export REDERR='2>'

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################

export DCOM_BASE=${DCOM_BASE:-${DCOMROOT}/prod}
export DCOM=${DCOM:-${DCOM_BASE}}
export COMIN=${COMIN:-$DCOM/$PDY/wgrbbul/fnmocens_gb2}
export COMINBC=${COMINBC:-$DCOM/$PDY/wgrbbul/fnmoc_ens_bc_gb2}
export COMINbias=${COMINbias:-${COMROOT}/${NET}/${envir}}

export COM_OUT=${COM_OUT:-${COMROOT}/${NET}/${envir}}

export COMOUT=$COM_OUT/${RUN}.${PDY}/${cyc}/pgrb2a
export COMOUTAN=$COM_OUT/${RUN}.${PDY}/${cyc}/pgrb2a_an
export COMOUTWT=$COM_OUT/${RUN}.${PDY}/${cyc}/pgrb2a_wt
export COMOUTBC=$COM_OUT/${RUN}.${PDY}/${cyc}/pgrb2a_bc

mkdir -m 775 -p ${COMOUT}
mkdir -m 775 -p ${COMOUTAN}
mkdir -m 775 -p ${COMOUTWT}
mkdir -m 775 -p ${COMOUTBC}

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

env

#####################
# Execute the scripts
#####################

runscript=$HOMEfnmoc/scripts/exnaefs_fnmoc_ens_debias.sh.ecf

hourlist=" 00  06  12  18  24  30  36  42  48  54  60  66  72  78  84  90  96 \
          102 108 114 120 126 132 138 144 150 156 162 168 174 180 186 192 198 \
          204 210 216 222 228 234 240 246 252 258 264 270 276 282 288 294 300 \
          306 312 318 324 330 336 342 348 354 360 366 372 378 384"

if [ -s $DATA/poescript ]; then
  rm -f $DATA/poescript
fi

for nhr in $hourlist; do
  mkdir -p $DATA/group.$nhr
  echo "$runscript \"$nhr\" $DATA/group.$nhr" >>$DATA/poescript
done

chmod +x $DATA/poescript
startmsg
$APRUN $DATA/poescript
export err=$?; err_chk
wait

#####################################
#  calculate ensemble mean and spread
#####################################

export DATAHOLD=$DATA

export DATA=$DATAHOLD/dir_avgspr_bc
mkdir -p $DATA
cd $DATA
$USHfnmoc/fnmocens_bc_avgspr.sh

export DATA=$DATAHOLD/dir_avgspr
mkdir -p $DATA
cd $DATA
$USHfnmoc/fnmocens_avgspr.sh                  

cat $DATAHOLD/group.06/$pgmout.06.p02_an
cat $DATAHOLD/group.06/$pgmout.06.p02_wt 
cat $DATAHOLD/group.360/$pgmout.360.p02_an

cat $DATAHOLD/dir_avgspr_bc/$pgmout.12_avgspr
cat $DATAHOLD/dir_avgspr/$pgmout.12_avgspr

cat $DATAHOLD/dir_avgspr_bc/$pgmout.360_avgspr
cat $DATAHOLD/dir_avgspr/$pgmout.360_avgspr

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
if [ $KEEPDATA != YES ]; then
  cd $DATAROOT
  rm -rf $DATA
  rm -rf $DATAHOLD
fi

date
