#!/bin/sh 
# #### 05/05/99 ###############################
# Daily Update Bias Estimation of CMC Ensemble              
# #############################################

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the sms script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}

set -xa

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-naefs}
export RUN=${RUN:-cmce}

#########################################
# Run config file to get input parameters
#########################################

if [ "$RUN_ENVIR" != nco ]      ### For Developers
then
  export PARA_CONFIG=${PARA_CONFIG:-${PACKAGEROOT}/${direxp}/parm/cmce_bias_config}
  . $PARA_CONFIG
fi

export PS4='$SECONDS + '
date

########################################################
# obtain unique process id (pid) and make temp directory
########################################################
export pid=$$
export DATAROOT=${DATAROOT:-/lfs/f1/ops/${envir}/tmp}
export DATA=$DATAROOT/${job}.${pid}

mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z

# JY module load grib_util
##################
# File To Log Msgs
##################

export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}

#####################################
# Determine Job Output Name on System
#####################################

export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

##############################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
##############################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}

#########################
# Specify Execution Areas
#########################

export HOMEcmce=${HOMEcmce:-${PACKAGEROOT}/naefs.${naefs_ver}}
export EXECcmce=${EXECcmce:-$HOMEcmce/exec}
export FIXcmce=${FIXcmce:-$HOMEcmce/fix}
export USHcmce=${USHcmce:-$HOMEcmce/ush}

export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg
export REDOUT='1>>'
export REDERR='2>'

#########################################
# Run setpdy and initialize PDY variables
#########################################
setpdy.sh
. ./PDY

####################################################################
# BIASMEM  - Calculate the Bias of One Ensemble Member
# BIASCDAS - Calculate the Difference Between GDAS and CDAS Analysis
# BIASAVG  - Calculate the Bias of Ensemble Average
# BIASC00  - Calculate the Bias of Ensemble Control Test
#####################################################################

export BIASMEM=NO 
export BIASCDAS=YES
export BIASAVG=NO 
export BIASC00=NO 

########################
# Define COM directories
########################

export COMINbias=${COMINbias:-$(compath.py $envir/$NET/${naefs_ver})}
export COM_CMC=${COM_CMC:-$(compath.py $envir/$NET/${naefs_ver})}
export COMINcfs=${COMINcfs:-$(compath.py ${envir}/com/cfs/${cfs_ver})}

export COM_OUT=${COM_OUT:-$(compath.py -o $NET/${naefs_ver})}
export COMOUT_M1=$COM_OUT/${RUN}.${PDYm1}/${cyc}/pgrb2ap5
export COMOUT_M2=$COM_OUT/${RUN}.${PDYm2}/${cyc}/pgrb2ap5

mkdir -m 775 -p ${COMOUT_M1}
mkdir -m 775 -p ${COMOUT_M2}

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

env

####################
# Execute the script
####################

$HOMEcmce/scripts/exnaefs_cmc_ens_bias.sh

cat $pgmout.*
msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

########################################
# Remove the Temporary working directory
########################################
if [ $KEEPDATA != YES ]; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
