#!/bin/sh
# ###########################################################################################
# This Job Updates Downscaling Vector Estimation Between RTMA and NCEP Analysis for Alaska Region
# ###########################################################################################

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the sms script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################

set -xa

export PS4='${PMI_FORK_RANK}: $SECONDS + '
date

###########################################
# Run config file to get input parameters
###########################################
if [ "$RUN_ENVIR" = dev ]      ### For Developers, "group_name" is passed from the SMS script
then
  export jlogfile=/dev/null
fi

########################################################
# obtain unique process id (pid) and make temp directory
########################################################
export pid=$$
export DATA=${DATA:-$DATAROOT/${job}.${pid}}
mkdir -p $DATA
export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

################################################################
# SENDCOM=YES--Copy output file to /com
# SENDECF=YES--Allow to talk back to ecFLOW
# SENDDBN=YES--Alert output file to TOC, set to NO for testing
################################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}          # need to set to NO for testing
export SENDECF=${SENDECF:-YES}

#
# Set up model and cycle specific variables
#
export NET=naefs
export RUN=naefs
#export fend=384
export finc=3
#export fstart=03
export model=ensemble
export GRIB=
export EXT=""

#
# Now set up GEMPAK/NTRANS environment
#
#. /nwprod/gempak/.gempak

#########################
# Specify Execution Areas
#########################

export HOMEnaefs=${HOMEnaefs:-$PACKAGEROOT/naefs.${naefs_ver}}
export EXECnaefs=${EXECnaefs:-$HOMEnaefs/exec}
export FIXnaefs=${FIXnaefs:-$HOMEnaefs/fix}
export USHnaefs=${USHnaefs:-$HOMEnaefs/ush}

###################################
# Set up the UTILITIES
###################################
# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY

#################################################
# Set up the INPUT and OUTPUT directories
#################################################

export COMIN=${COMIN:-$(compath.py $envir/$NET/${naefs_ver})/${RUN}.${PDY}/${cyc}/ndgd_gb2}
export COMOUT=${COMOUT:-$(compath.py -o $NET/${naefs_ver})/${RUN}.${PDY}/gempak}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi

env

####################
# Execute the script 
####################

hourlist="000 003 006 009 012 015 018 021 024 027 030 033 036 039 042 045 048 \
          051 054 057 060 063 066 069 072 075 078 081 084 087 090 093 096 099 \
          102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 \
          153 156 159 162 165 168 171 174 177 180 183 186 189 192 198 204 \
          210 216 222 228 234 240 246 252 258 264 270 276 282 288 294 300 \
          306 312 318 324 330 336 342 348 354 360 366 372 378 384"

for nfhrs in $hourlist; do
  fstart=$nfhrs
  fend=$nfhrs
  mkdir -p $DATA/dir_${nfhrs}
  if [ -s poe_gempak_${nfhrs} ]; then rm poe_gempak_${nfhrs}; fi
  for member in 10pt 50pt 90pt avg spr mode; do
    export DBN_ALERT_TYPE=NAEFS_NDGD_GEMPAK
    echo "${HOMEnaefs}/scripts/exnawips_naefs.sh $DATA/dir_${nfhrs} \
    $fstart $fend $COMIN $COMOUT naefs ndgd_alaska ${DBN_ALERT_TYPE} $member &> \
    $DATA/dir_${nfhrs}/output_ge${member}_$nfhrs" >> $DATA/poe_gempak_${nfhrs}
  done
done

if [ -s poescript_gempak ]; then rm poescript_gempak; fi

for nfhrs in $hourlist; do
  chmod 775 $DATA/poe_gempak_${nfhrs}
  echo ". ./poe_gempak_${nfhrs}" >>poescript_gempak
done

chmod 775 $DATA/poescript_gempak

# Execute the script.
$APRUN $DATA/poescript_gempak      
export err=$?; err_chk

cat $DATA/dir_024/output_gemode_024
cat $DATA/dir_384/output_gemode_384
cat $DATA/dir_024/output_geavg_024
cat $DATA/dir_384/output_geavg_384
########################################################

cd $DATAROOT

if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
