#!/bin/ksh

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='${PMI_FORK_RANK}: $SECONDS + ' 
date
# 
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA=${DATA:-$DATAROOT/${job}.${pid}}
mkdir $DATA
cd $DATA 

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

####################################
# File To Log Msgs
####################################
if [ ${RUN_ENVIR} = dev ]; then
   # DEV
  export jlogfile=/dev/null
fi
export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}

####################################
# SENDSMS  - Flag Events on SMS
# SENDDBN  - Issue DBNet Client Calls
# SENDCOM  - Copy files to /com directory
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDSMS=${SENDSMS:-YES}
export SENDDBN=${SENDDBN:-YES}

#
# Set up model and cycle specific variables
#
export NET=naefs
export RUN=gefs
export fend=384
export finc=6
export fstart=06
export model=ensemble
export GRIB=
export EXT=""
export DBN_ALERT_TYPE=NAEFS_GEFS_GEMPAK

#
# Now set up GEMPAK/NTRANS environment
#
#. /nwprod/gempak/.gempak
#. /gpfs/hps/nco/ops/nwprod/gempak.v6.32.0/.gempak


#########################
# Specify Execution Areas
#########################

export HOMEnaefs=${HOMEnaefs:-$NWROOT/naefs.${model_ver}}
export EXECnaefs=${EXECnaefs:-$HOMEnaefs/exec}
export FIXnaefs=${FIXnaefs:-$HOMEnaefs/fix}
export USHnaefs=${USHnaefs:-$HOMEnaefs/ush}

###################################
# Set up the UTILITIES
###################################
# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

export COM_IN=${COM_IN:-$COMROOT/${NET}/${ver}}
export COMIN1=$COM_IN/${RUN}.${PDY}/${cyc}/prcp_gb2
export COMIN2=$COM_IN/${RUN}.${PDY}/${cyc}/prcp_bc_gb2
export COMOUT=${COMOUT:-$COMROOT/nawips/${nawips_ver}/${RUN}.${PDY}/prcp}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi
 
env

DATAHOLD=$DATA

########################################################
# Execute the script.

mkdir -m 775 $DATA/24h_pqpf
echo "${HOMEnaefs}/scripts/exnawips_gefs_enscqpf.sh $DATA/24h_pqpf 24 384 $COMIN1 $COMOUT gepqpf 24h NAEFS_GEFS_GEMPAK &> $DATA/24h_pqpf/output" >> $DATA/poescript

for ftype in pqpf prcp 
do
  for hrinter in bc_24h bc_06h
  do
    mkdir -m 775 $DATA/${hrinter}_${ftype}
      echo "${HOMEnaefs}/scripts/exnawips_gefs_enscqpf.sh $DATA/${hrinter}_${ftype} 06 384 $COMIN2 $COMOUT ge${ftype} $hrinter NAEFS_GEFS_GEMPAK &> $DATA/${hrinter}_${ftype}/output" >> $DATA/poescript
  done
done

mkdir -m 775 $DATA/24h_anv
echo "${HOMEnaefs}/scripts/exnawips_gefs_enscqpf.sh $DATA/24h_anv 24 384 $COMIN2 $COMOUT geprcp anv NAEFS_GEFS_GEMPAK &> $DATA/24h_anv/output" >> $DATA/poescript

mkdir -m 775 $DATA/24h_efi
echo "${HOMEnaefs}/scripts/exnawips_gefs_enscqpf.sh $DATA/24h_efi 24 384 $COMIN2 $COMOUT geprcp efi NAEFS_GEFS_GEMPAK &> $DATA/24h_efi/output" >> $DATA/poescript

chmod 775 $DATA/poescript

# Execute the script.
$APRUN $DATA/poescript
export err=$?; err_chk
cd $DATA
cat 24h_pqpf/output 

########################################################

cd $DATAROOT

if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
