#!/bin/sh

########################################
# Runs CMC Postprocessing
########################################

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='${PMI_FORK_RANK}: $SECONDS + ' 
date
# 
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA=${DATA:-$DATAROOT/${job}.${pid}}
mkdir $DATA
cd $DATA 

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

####################################
# File To Log Msgs
####################################

export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}

####################################
#
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

#
# Set up model and cycle specific variables
#
export NET=naefs
export RUN=cmce
#export fend=384
export finc=6
#export fstart=00
export model=ensemble
export GRIB=
export EXT=""
export DBN_ALERT_TYPE=NAEFS_CMCENS_GEMPAK

#
# Now set up GEMPAK/NTRANS environment
#
#. /nwprod/gempak/.gempak

#########################
# Specify Execution Areas
#########################

export HOMEnaefs=${HOMEnaefs:-$PACKAGEROOT/naefs.${naefs_ver}}

# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY

export COMIN=${COMIN:-$(compath.py $envir/$NET/${naefs_ver})/${RUN}.${PDY}/${cyc}/pgrb2ap5}
export COMOUT=${COMOUT:-$(compath.py -o $NET/${naefs_ver})/${RUN}.${PDY}/gempak}


if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi
 
env

DATAHOLD=$DATA

####################
# Execute the script 
####################

memberlist="c00 p01 p02 p03 p04 p05 p06 p07 p08 p09 p10 \
            p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 avg "

hourlist="000 003 006 009 012 015 018 021 024 027 030 033 036 039 042 045 048 \
          051 054 057 060 063 066 069 072 075 078 081 084 087 090 093 096 099 \
          102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 \
          153 156 159 162 165 168 171 174 177 180 183 186 189 192 198 204 \
          210 216 222 228 234 240 246 252 258 264 270 276 282 288 294 300 \
          306 312 318 324 330 336 342 348 354 360 366 372 378 384"

for nfhrs in $hourlist; do
  fstart=$nfhrs
  fend=$nfhrs
  if [ -s poe_gempak_${nfhrs} ]; then rm poe_gempak_${nfhrs}; fi
  mkdir -m 775 $DATA/dir_${nfhrs}
  for member in $memberlist; do
    export SUBRUN=cmc_ge${member}
    echo "${HOMEnaefs}/scripts/exnawips_cmce.sh $DATA/dir_${nfhrs} $fstart $fend $SUBRUN $member &> \
    $DATA/dir_${nfhrs}/output_${member}_${nfhrs}" >> $DATA/poe_gempak_${nfhrs}
  done
done

# Execute the script.

if [ -s poescript_gempak ]; then rm poescript_gempak; fi
for nfhrs in $hourlist; do
  chmod +x poe_gempak_${nfhrs}
  echo ". ./poe_gempak_${nfhrs}" >>poescript_gempak
done

chmod 775 $DATA/poescript_gempak
startmsg
$APRUN poescript_gempak
export err=$?; err_chk

cat $DATA/dir_024/output_p01_024
cat $DATA/dir_360/output_p01_360
cat $DATA/dir_024/output_avg_024
cat $DATA/dir_360/output_avg_360

########################################################

cd $DATAROOT

if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
